# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zio-control.ui'
#
# Created: Mon Apr 22 18:18:25 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_zio_control(object):
    def setupUi(self, zio_control):
        zio_control.setObjectName(_fromUtf8("zio_control"))
        zio_control.resize(664, 568)
        self.centralwidget = QtGui.QWidget(zio_control)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.lbl_nsample = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_nsample.setFont(font)
        self.lbl_nsample.setObjectName(_fromUtf8("lbl_nsample"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_nsample)
        self.edt_nsample = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_nsample.setFont(font)
        self.edt_nsample.setText(_fromUtf8(""))
        self.edt_nsample.setObjectName(_fromUtf8("edt_nsample"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.edt_nsample)
        self.lbl_ssize = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_ssize.setFont(font)
        self.lbl_ssize.setObjectName(_fromUtf8("lbl_ssize"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_ssize)
        self.edt_ssize = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_ssize.setFont(font)
        self.edt_ssize.setText(_fromUtf8(""))
        self.edt_ssize.setObjectName(_fromUtf8("edt_ssize"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.edt_ssize)
        self.lbl_nbits = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_nbits.setFont(font)
        self.lbl_nbits.setObjectName(_fromUtf8("lbl_nbits"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_nbits)
        self.edt_nbits = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_nbits.setFont(font)
        self.edt_nbits.setText(_fromUtf8(""))
        self.edt_nbits.setObjectName(_fromUtf8("edt_nbits"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.edt_nbits)
        self.gridLayout_2.addWidget(self.groupBox, 4, 2, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.ckb_lock_field = QtGui.QCheckBox(self.groupBox_4)
        self.ckb_lock_field.setChecked(False)
        self.ckb_lock_field.setObjectName(_fromUtf8("ckb_lock_field"))
        self.horizontalLayout_4.addWidget(self.ckb_lock_field)
        self.gridLayout_2.addWidget(self.groupBox_4, 2, 0, 1, 3)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.btn_get = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_get.setFont(font)
        self.btn_get.setObjectName(_fromUtf8("btn_get"))
        self.gridLayout_7.addWidget(self.btn_get, 0, 0, 1, 1)
        self.btn_set = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_set.setFont(font)
        self.btn_set.setObjectName(_fromUtf8("btn_set"))
        self.gridLayout_7.addWidget(self.btn_set, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_7, 0, 2, 1, 1)
        self.formLayout_11 = QtGui.QFormLayout()
        self.formLayout_11.setObjectName(_fromUtf8("formLayout_11"))
        self.lbl_file = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_file.setFont(font)
        self.lbl_file.setObjectName(_fromUtf8("lbl_file"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_file)
        self.edt_file = QtGui.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_file.setFont(font)
        self.edt_file.setObjectName(_fromUtf8("edt_file"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.FieldRole, self.edt_file)
        self.gridLayout_2.addLayout(self.formLayout_11, 0, 0, 1, 2)
        self.grp_address = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.grp_address.setFont(font)
        self.grp_address.setObjectName(_fromUtf8("grp_address"))
        self.gridLayout = QtGui.QGridLayout(self.grp_address)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.lbl_hosttype = QtGui.QLabel(self.grp_address)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_hosttype.setFont(font)
        self.lbl_hosttype.setObjectName(_fromUtf8("lbl_hosttype"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_hosttype)
        self.edt_hosttype = QtGui.QLineEdit(self.grp_address)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_hosttype.setFont(font)
        self.edt_hosttype.setText(_fromUtf8(""))
        self.edt_hosttype.setObjectName(_fromUtf8("edt_hosttype"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.edt_hosttype)
        self.lbl_hostid = QtGui.QLabel(self.grp_address)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_hostid.setFont(font)
        self.lbl_hostid.setObjectName(_fromUtf8("lbl_hostid"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_hostid)
        self.edt_hostid = QtGui.QLineEdit(self.grp_address)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_hostid.setFont(font)
        self.edt_hostid.setText(_fromUtf8(""))
        self.edt_hostid.setObjectName(_fromUtf8("edt_hostid"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.edt_hostid)
        self.lbl_devid = QtGui.QLabel(self.grp_address)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_devid.setFont(font)
        self.lbl_devid.setObjectName(_fromUtf8("lbl_devid"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_devid)
        self.edt_devid = QtGui.QLineEdit(self.grp_address)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_devid.setFont(font)
        self.edt_devid.setText(_fromUtf8(""))
        self.edt_devid.setObjectName(_fromUtf8("edt_devid"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.edt_devid)
        self.gridLayout.addLayout(self.formLayout_5, 0, 0, 1, 1)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.lbl_devname = QtGui.QLabel(self.grp_address)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_devname.setFont(font)
        self.lbl_devname.setObjectName(_fromUtf8("lbl_devname"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_devname)
        self.edt_devname = QtGui.QLineEdit(self.grp_address)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_devname.setFont(font)
        self.edt_devname.setText(_fromUtf8(""))
        self.edt_devname.setObjectName(_fromUtf8("edt_devname"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.edt_devname)
        self.lbl_cset = QtGui.QLabel(self.grp_address)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_cset.setFont(font)
        self.lbl_cset.setObjectName(_fromUtf8("lbl_cset"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_cset)
        self.edt_cset = QtGui.QLineEdit(self.grp_address)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_cset.setFont(font)
        self.edt_cset.setText(_fromUtf8(""))
        self.edt_cset.setObjectName(_fromUtf8("edt_cset"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.edt_cset)
        self.lbl_chan = QtGui.QLabel(self.grp_address)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_chan.setFont(font)
        self.lbl_chan.setObjectName(_fromUtf8("lbl_chan"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_chan)
        self.edt_chan = QtGui.QLineEdit(self.grp_address)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_chan.setFont(font)
        self.edt_chan.setText(_fromUtf8(""))
        self.edt_chan.setObjectName(_fromUtf8("edt_chan"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.edt_chan)
        self.gridLayout.addLayout(self.formLayout_4, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.grp_address, 4, 0, 1, 2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 3)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_6 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.ldl_alarm_dev = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ldl_alarm_dev.setFont(font)
        self.ldl_alarm_dev.setObjectName(_fromUtf8("ldl_alarm_dev"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.ldl_alarm_dev)
        self.edt_alarm_dev = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_alarm_dev.setFont(font)
        self.edt_alarm_dev.setText(_fromUtf8(""))
        self.edt_alarm_dev.setObjectName(_fromUtf8("edt_alarm_dev"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.edt_alarm_dev)
        self.lbl_alarm_zio = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_alarm_zio.setFont(font)
        self.lbl_alarm_zio.setObjectName(_fromUtf8("lbl_alarm_zio"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_alarm_zio)
        self.edt_alarm_zio = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_alarm_zio.setFont(font)
        self.edt_alarm_zio.setText(_fromUtf8(""))
        self.edt_alarm_zio.setObjectName(_fromUtf8("edt_alarm_zio"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.edt_alarm_zio)
        self.gridLayout_2.addWidget(self.groupBox_2, 3, 1, 1, 1)
        self.grp_timestamp = QtGui.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.grp_timestamp.setFont(font)
        self.grp_timestamp.setObjectName(_fromUtf8("grp_timestamp"))
        self.formLayout_2 = QtGui.QFormLayout(self.grp_timestamp)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lbl_sec = QtGui.QLabel(self.grp_timestamp)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_sec.setFont(font)
        self.lbl_sec.setObjectName(_fromUtf8("lbl_sec"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_sec)
        self.edt_sec = QtGui.QLineEdit(self.grp_timestamp)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_sec.setFont(font)
        self.edt_sec.setText(_fromUtf8(""))
        self.edt_sec.setObjectName(_fromUtf8("edt_sec"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.edt_sec)
        self.lbl_ticks = QtGui.QLabel(self.grp_timestamp)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_ticks.setFont(font)
        self.lbl_ticks.setObjectName(_fromUtf8("lbl_ticks"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_ticks)
        self.edt_ticks = QtGui.QLineEdit(self.grp_timestamp)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_ticks.setFont(font)
        self.edt_ticks.setText(_fromUtf8(""))
        self.edt_ticks.setObjectName(_fromUtf8("edt_ticks"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.edt_ticks)
        self.lbl_bins = QtGui.QLabel(self.grp_timestamp)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_bins.setFont(font)
        self.lbl_bins.setObjectName(_fromUtf8("lbl_bins"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_bins)
        self.edt_bins = QtGui.QLineEdit(self.grp_timestamp)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_bins.setFont(font)
        self.edt_bins.setText(_fromUtf8(""))
        self.edt_bins.setObjectName(_fromUtf8("edt_bins"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.edt_bins)
        self.gridLayout_2.addWidget(self.grp_timestamp, 3, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbl_version = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_version.setFont(font)
        self.lbl_version.setObjectName(_fromUtf8("lbl_version"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_version)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.edt_vm1 = QtGui.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_vm1.setFont(font)
        self.edt_vm1.setText(_fromUtf8(""))
        self.edt_vm1.setObjectName(_fromUtf8("edt_vm1"))
        self.gridLayout_6.addWidget(self.edt_vm1, 0, 1, 1, 1)
        self.edt_vm2 = QtGui.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_vm2.setFont(font)
        self.edt_vm2.setText(_fromUtf8(""))
        self.edt_vm2.setObjectName(_fromUtf8("edt_vm2"))
        self.gridLayout_6.addWidget(self.edt_vm2, 0, 2, 1, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.gridLayout_6)
        self.lbl_flags = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_flags.setFont(font)
        self.lbl_flags.setObjectName(_fromUtf8("lbl_flags"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_flags)
        self.edt_flags = QtGui.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_flags.setFont(font)
        self.edt_flags.setText(_fromUtf8(""))
        self.edt_flags.setObjectName(_fromUtf8("edt_flags"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.edt_flags)
        self.lbl_nseq = QtGui.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_nseq.setFont(font)
        self.lbl_nseq.setObjectName(_fromUtf8("lbl_nseq"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_nseq)
        self.edt_nseq = QtGui.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_nseq.setFont(font)
        self.edt_nseq.setText(_fromUtf8(""))
        self.edt_nseq.setObjectName(_fromUtf8("edt_nseq"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.edt_nseq)
        self.gridLayout_2.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.tab_attributes = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tab_attributes.setFont(font)
        self.tab_attributes.setObjectName(_fromUtf8("tab_attributes"))
        self.tab_dev = QtGui.QWidget()
        self.tab_dev.setObjectName(_fromUtf8("tab_dev"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_dev)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lyt_frm_dev = QtGui.QFormLayout()
        self.lyt_frm_dev.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.lyt_frm_dev.setObjectName(_fromUtf8("lyt_frm_dev"))
        self.lbl_dev_name = QtGui.QLabel(self.tab_dev)
        self.lbl_dev_name.setObjectName(_fromUtf8("lbl_dev_name"))
        self.lyt_frm_dev.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_dev_name)
        self.edt_dev_name = QtGui.QLineEdit(self.tab_dev)
        self.edt_dev_name.setText(_fromUtf8(""))
        self.edt_dev_name.setObjectName(_fromUtf8("edt_dev_name"))
        self.lyt_frm_dev.setWidget(0, QtGui.QFormLayout.FieldRole, self.edt_dev_name)
        self.lbl_dev_stdmask = QtGui.QLabel(self.tab_dev)
        self.lbl_dev_stdmask.setObjectName(_fromUtf8("lbl_dev_stdmask"))
        self.lyt_frm_dev.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_dev_stdmask)
        self.edt_dev_stdmask = QtGui.QLineEdit(self.tab_dev)
        self.edt_dev_stdmask.setText(_fromUtf8(""))
        self.edt_dev_stdmask.setObjectName(_fromUtf8("edt_dev_stdmask"))
        self.lyt_frm_dev.setWidget(1, QtGui.QFormLayout.FieldRole, self.edt_dev_stdmask)
        self.lbl_dev_extmask = QtGui.QLabel(self.tab_dev)
        self.lbl_dev_extmask.setObjectName(_fromUtf8("lbl_dev_extmask"))
        self.lyt_frm_dev.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_dev_extmask)
        self.edt_dev_extmask = QtGui.QLineEdit(self.tab_dev)
        self.edt_dev_extmask.setText(_fromUtf8(""))
        self.edt_dev_extmask.setObjectName(_fromUtf8("edt_dev_extmask"))
        self.lyt_frm_dev.setWidget(2, QtGui.QFormLayout.FieldRole, self.edt_dev_extmask)
        self.gridLayout_5.addLayout(self.lyt_frm_dev, 0, 0, 1, 1)
        self.grp_dev_stdattr = QtGui.QGroupBox(self.tab_dev)
        self.grp_dev_stdattr.setObjectName(_fromUtf8("grp_dev_stdattr"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.grp_dev_stdattr)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.scrl_dev_std = QtGui.QScrollArea(self.grp_dev_stdattr)
        self.scrl_dev_std.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrl_dev_std.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrl_dev_std.setWidgetResizable(True)
        self.scrl_dev_std.setObjectName(_fromUtf8("scrl_dev_std"))
        self.scrl_dev_std_content = QtGui.QWidget()
        self.scrl_dev_std_content.setGeometry(QtCore.QRect(0, -46, 218, 174))
        self.scrl_dev_std_content.setObjectName(_fromUtf8("scrl_dev_std_content"))
        self.formLayout_8 = QtGui.QFormLayout(self.scrl_dev_std_content)
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.lbl_dev_nbit = QtGui.QLabel(self.scrl_dev_std_content)
        self.lbl_dev_nbit.setObjectName(_fromUtf8("lbl_dev_nbit"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_dev_nbit)
        self.edt_dev_nbit = QtGui.QLineEdit(self.scrl_dev_std_content)
        self.edt_dev_nbit.setText(_fromUtf8(""))
        self.edt_dev_nbit.setObjectName(_fromUtf8("edt_dev_nbit"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.edt_dev_nbit)
        self.lbl_dev_gain = QtGui.QLabel(self.scrl_dev_std_content)
        self.lbl_dev_gain.setObjectName(_fromUtf8("lbl_dev_gain"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_dev_gain)
        self.edt_dev_gain = QtGui.QLineEdit(self.scrl_dev_std_content)
        self.edt_dev_gain.setText(_fromUtf8(""))
        self.edt_dev_gain.setObjectName(_fromUtf8("edt_dev_gain"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.edt_dev_gain)
        self.lbl_dev_offset = QtGui.QLabel(self.scrl_dev_std_content)
        self.lbl_dev_offset.setObjectName(_fromUtf8("lbl_dev_offset"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_dev_offset)
        self.edt_dev_offset = QtGui.QLineEdit(self.scrl_dev_std_content)
        self.edt_dev_offset.setText(_fromUtf8(""))
        self.edt_dev_offset.setObjectName(_fromUtf8("edt_dev_offset"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.FieldRole, self.edt_dev_offset)
        self.lbl_dev_vref = QtGui.QLabel(self.scrl_dev_std_content)
        self.lbl_dev_vref.setObjectName(_fromUtf8("lbl_dev_vref"))
        self.formLayout_8.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbl_dev_vref)
        self.edt_dev_vref = QtGui.QLineEdit(self.scrl_dev_std_content)
        self.edt_dev_vref.setText(_fromUtf8(""))
        self.edt_dev_vref.setObjectName(_fromUtf8("edt_dev_vref"))
        self.formLayout_8.setWidget(5, QtGui.QFormLayout.FieldRole, self.edt_dev_vref)
        self.lbl_dev_rate = QtGui.QLabel(self.scrl_dev_std_content)
        self.lbl_dev_rate.setObjectName(_fromUtf8("lbl_dev_rate"))
        self.formLayout_8.setWidget(6, QtGui.QFormLayout.LabelRole, self.lbl_dev_rate)
        self.edt_dev_rate = QtGui.QLineEdit(self.scrl_dev_std_content)
        self.edt_dev_rate.setText(_fromUtf8(""))
        self.edt_dev_rate.setObjectName(_fromUtf8("edt_dev_rate"))
        self.formLayout_8.setWidget(6, QtGui.QFormLayout.FieldRole, self.edt_dev_rate)
        self.label = QtGui.QLabel(self.scrl_dev_std_content)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_8.setWidget(7, QtGui.QFormLayout.LabelRole, self.label)
        self.edt_dev_version = QtGui.QLineEdit(self.scrl_dev_std_content)
        self.edt_dev_version.setObjectName(_fromUtf8("edt_dev_version"))
        self.formLayout_8.setWidget(7, QtGui.QFormLayout.FieldRole, self.edt_dev_version)
        self.scrl_dev_std.setWidget(self.scrl_dev_std_content)
        self.verticalLayout_6.addWidget(self.scrl_dev_std)
        self.gridLayout_5.addWidget(self.grp_dev_stdattr, 0, 1, 1, 1)
        self.grp_dev_extattr = QtGui.QGroupBox(self.tab_dev)
        self.grp_dev_extattr.setObjectName(_fromUtf8("grp_dev_extattr"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.grp_dev_extattr)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.scrl_dev_ext = QtGui.QScrollArea(self.grp_dev_extattr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrl_dev_ext.sizePolicy().hasHeightForWidth())
        self.scrl_dev_ext.setSizePolicy(sizePolicy)
        self.scrl_dev_ext.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrl_dev_ext.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrl_dev_ext.setWidgetResizable(True)
        self.scrl_dev_ext.setObjectName(_fromUtf8("scrl_dev_ext"))
        self.scrl_dev_ext_content = QtGui.QWidget()
        self.scrl_dev_ext_content.setGeometry(QtCore.QRect(0, 0, 216, 120))
        self.scrl_dev_ext_content.setObjectName(_fromUtf8("scrl_dev_ext_content"))
        self.lyt_frm_trg_ext = QtGui.QFormLayout(self.scrl_dev_ext_content)
        self.lyt_frm_trg_ext.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.lyt_frm_trg_ext.setObjectName(_fromUtf8("lyt_frm_trg_ext"))
        self.scrl_dev_ext.setWidget(self.scrl_dev_ext_content)
        self.verticalLayout_8.addWidget(self.scrl_dev_ext)
        self.gridLayout_5.addWidget(self.grp_dev_extattr, 0, 2, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 20)
        self.gridLayout_5.setColumnStretch(1, 40)
        self.gridLayout_5.setColumnStretch(2, 40)
        self.tab_attributes.addTab(self.tab_dev, _fromUtf8(""))
        self.tab_trg = QtGui.QWidget()
        self.tab_trg.setObjectName(_fromUtf8("tab_trg"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_trg)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lyt_frm_trg = QtGui.QFormLayout()
        self.lyt_frm_trg.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.lyt_frm_trg.setObjectName(_fromUtf8("lyt_frm_trg"))
        self.lbl_trg_name = QtGui.QLabel(self.tab_trg)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_trg_name.setFont(font)
        self.lbl_trg_name.setObjectName(_fromUtf8("lbl_trg_name"))
        self.lyt_frm_trg.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_trg_name)
        self.cmb_trg_name = QtGui.QComboBox(self.tab_trg)
        self.cmb_trg_name.setObjectName(_fromUtf8("cmb_trg_name"))
        self.lyt_frm_trg.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmb_trg_name)
        self.lbl_trg_stdmask = QtGui.QLabel(self.tab_trg)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_trg_stdmask.setFont(font)
        self.lbl_trg_stdmask.setObjectName(_fromUtf8("lbl_trg_stdmask"))
        self.lyt_frm_trg.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_trg_stdmask)
        self.edt_trg_stdmask = QtGui.QLineEdit(self.tab_trg)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_trg_stdmask.setFont(font)
        self.edt_trg_stdmask.setText(_fromUtf8(""))
        self.edt_trg_stdmask.setObjectName(_fromUtf8("edt_trg_stdmask"))
        self.lyt_frm_trg.setWidget(1, QtGui.QFormLayout.FieldRole, self.edt_trg_stdmask)
        self.lbl_trg_extmask = QtGui.QLabel(self.tab_trg)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_trg_extmask.setFont(font)
        self.lbl_trg_extmask.setObjectName(_fromUtf8("lbl_trg_extmask"))
        self.lyt_frm_trg.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_trg_extmask)
        self.edt_trg_extmask = QtGui.QLineEdit(self.tab_trg)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.edt_trg_extmask.setFont(font)
        self.edt_trg_extmask.setText(_fromUtf8(""))
        self.edt_trg_extmask.setObjectName(_fromUtf8("edt_trg_extmask"))
        self.lyt_frm_trg.setWidget(2, QtGui.QFormLayout.FieldRole, self.edt_trg_extmask)
        self.gridLayout_4.addLayout(self.lyt_frm_trg, 0, 0, 1, 1)
        self.grp_trg_stdattr = QtGui.QGroupBox(self.tab_trg)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.grp_trg_stdattr.setFont(font)
        self.grp_trg_stdattr.setObjectName(_fromUtf8("grp_trg_stdattr"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.grp_trg_stdattr)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.scrl_trg_std = QtGui.QScrollArea(self.grp_trg_stdattr)
        self.scrl_trg_std.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrl_trg_std.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrl_trg_std.setWidgetResizable(True)
        self.scrl_trg_std.setObjectName(_fromUtf8("scrl_trg_std"))
        self.scrl_trg_std_content = QtGui.QWidget()
        self.scrl_trg_std_content.setGeometry(QtCore.QRect(0, 0, 204, 120))
        self.scrl_trg_std_content.setObjectName(_fromUtf8("scrl_trg_std_content"))
        self.formLayout_7 = QtGui.QFormLayout(self.scrl_trg_std_content)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.lbl_trg_nshot = QtGui.QLabel(self.scrl_trg_std_content)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        self.lbl_trg_nshot.setFont(font)
        self.lbl_trg_nshot.setObjectName(_fromUtf8("lbl_trg_nshot"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_trg_nshot)
        self.edt_trg_nshot = QtGui.QLineEdit(self.scrl_trg_std_content)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        self.edt_trg_nshot.setFont(font)
        self.edt_trg_nshot.setText(_fromUtf8(""))
        self.edt_trg_nshot.setObjectName(_fromUtf8("edt_trg_nshot"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.edt_trg_nshot)
        self.lbl_trg_pre = QtGui.QLabel(self.scrl_trg_std_content)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        self.lbl_trg_pre.setFont(font)
        self.lbl_trg_pre.setObjectName(_fromUtf8("lbl_trg_pre"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl_trg_pre)
        self.lbl_trg_post = QtGui.QLabel(self.scrl_trg_std_content)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        self.lbl_trg_post.setFont(font)
        self.lbl_trg_post.setObjectName(_fromUtf8("lbl_trg_post"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_trg_post)
        self.edt_trg_post = QtGui.QLineEdit(self.scrl_trg_std_content)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        self.edt_trg_post.setFont(font)
        self.edt_trg_post.setText(_fromUtf8(""))
        self.edt_trg_post.setObjectName(_fromUtf8("edt_trg_post"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.edt_trg_post)
        self.edt_trg_pre = QtGui.QLineEdit(self.scrl_trg_std_content)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        self.edt_trg_pre.setFont(font)
        self.edt_trg_pre.setText(_fromUtf8(""))
        self.edt_trg_pre.setObjectName(_fromUtf8("edt_trg_pre"))
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.edt_trg_pre)
        self.edt_trg_version = QtGui.QLineEdit(self.scrl_trg_std_content)
        self.edt_trg_version.setReadOnly(True)
        self.edt_trg_version.setObjectName(_fromUtf8("edt_trg_version"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.FieldRole, self.edt_trg_version)
        self.label_2 = QtGui.QLabel(self.scrl_trg_std_content)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_7.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_2)
        self.scrl_trg_std.setWidget(self.scrl_trg_std_content)
        self.verticalLayout_11.addWidget(self.scrl_trg_std)
        self.gridLayout_4.addWidget(self.grp_trg_stdattr, 0, 1, 1, 1)
        self.grp_trg_extattr = QtGui.QGroupBox(self.tab_trg)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.grp_trg_extattr.setFont(font)
        self.grp_trg_extattr.setObjectName(_fromUtf8("grp_trg_extattr"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.grp_trg_extattr)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.scrl_trg_ext = QtGui.QScrollArea(self.grp_trg_extattr)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.scrl_trg_ext.setFont(font)
        self.scrl_trg_ext.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrl_trg_ext.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrl_trg_ext.setWidgetResizable(True)
        self.scrl_trg_ext.setObjectName(_fromUtf8("scrl_trg_ext"))
        self.scrl_trg_ext_content = QtGui.QWidget()
        self.scrl_trg_ext_content.setGeometry(QtCore.QRect(0, 0, 203, 120))
        self.scrl_trg_ext_content.setObjectName(_fromUtf8("scrl_trg_ext_content"))
        self.lyt_frm_dev_ext = QtGui.QFormLayout(self.scrl_trg_ext_content)
        self.lyt_frm_dev_ext.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.lyt_frm_dev_ext.setObjectName(_fromUtf8("lyt_frm_dev_ext"))
        self.scrl_trg_ext.setWidget(self.scrl_trg_ext_content)
        self.verticalLayout_12.addWidget(self.scrl_trg_ext)
        self.gridLayout_4.addWidget(self.grp_trg_extattr, 0, 2, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 20)
        self.gridLayout_4.setColumnStretch(1, 40)
        self.gridLayout_4.setColumnStretch(2, 40)
        self.tab_attributes.addTab(self.tab_trg, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tab_attributes, 5, 0, 1, 3)
        zio_control.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(zio_control)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        zio_control.setStatusBar(self.statusbar)

        self.retranslateUi(zio_control)
        self.tab_attributes.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(zio_control)

    def retranslateUi(self, zio_control):
        zio_control.setWindowTitle(_translate("zio_control", "ZIO CONTROL GUI", None))
        self.groupBox.setTitle(_translate("zio_control", "Samples", None))
        self.lbl_nsample.setText(_translate("zio_control", "N. samples", None))
        self.lbl_ssize.setText(_translate("zio_control", "Sample size", None))
        self.lbl_nbits.setText(_translate("zio_control", "Sample bits", None))
        self.groupBox_4.setTitle(_translate("zio_control", "Options", None))
        self.ckb_lock_field.setText(_translate("zio_control", "Lock unmutable fields", None))
        self.btn_get.setText(_translate("zio_control", "GET", None))
        self.btn_set.setText(_translate("zio_control", "SET", None))
        self.lbl_file.setText(_translate("zio_control", "Control source file", None))
        self.grp_address.setTitle(_translate("zio_control", "ZIO address", None))
        self.lbl_hosttype.setText(_translate("zio_control", "Host type", None))
        self.lbl_hostid.setText(_translate("zio_control", "Host ID", None))
        self.lbl_devid.setText(_translate("zio_control", "Device ID", None))
        self.lbl_devname.setText(_translate("zio_control", "Device name", None))
        self.lbl_cset.setText(_translate("zio_control", "Channel set", None))
        self.lbl_chan.setText(_translate("zio_control", "Channel", None))
        self.groupBox_2.setTitle(_translate("zio_control", "Alarms", None))
        self.ldl_alarm_dev.setText(_translate("zio_control", "Device", None))
        self.lbl_alarm_zio.setText(_translate("zio_control", "ZIO", None))
        self.grp_timestamp.setTitle(_translate("zio_control", "Time stamp", None))
        self.lbl_sec.setText(_translate("zio_control", "Seconds", None))
        self.lbl_ticks.setText(_translate("zio_control", "Ticks", None))
        self.lbl_bins.setText(_translate("zio_control", "Bins", None))
        self.groupBox_3.setTitle(_translate("zio_control", "Generic Info", None))
        self.lbl_version.setText(_translate("zio_control", "ZIO Version", None))
        self.lbl_flags.setText(_translate("zio_control", "Flags", None))
        self.lbl_nseq.setText(_translate("zio_control", "N. sequence", None))
        self.lbl_dev_name.setText(_translate("zio_control", "Name", None))
        self.lbl_dev_stdmask.setText(_translate("zio_control", "std mask", None))
        self.lbl_dev_extmask.setText(_translate("zio_control", "ext mask", None))
        self.grp_dev_stdattr.setTitle(_translate("zio_control", "Standard attributes", None))
        self.lbl_dev_nbit.setText(_translate("zio_control", "resolution-bits", None))
        self.lbl_dev_gain.setText(_translate("zio_control", "gain_factor", None))
        self.lbl_dev_offset.setText(_translate("zio_control", "offset", None))
        self.lbl_dev_vref.setText(_translate("zio_control", "vref-src", None))
        self.lbl_dev_rate.setText(_translate("zio_control", "max-sample-rate", None))
        self.label.setText(_translate("zio_control", "version", None))
        self.grp_dev_extattr.setTitle(_translate("zio_control", "Extended attributes", None))
        self.tab_attributes.setTabText(self.tab_attributes.indexOf(self.tab_dev), _translate("zio_control", "Device", None))
        self.lbl_trg_name.setText(_translate("zio_control", "Name", None))
        self.lbl_trg_stdmask.setText(_translate("zio_control", "std mask", None))
        self.lbl_trg_extmask.setText(_translate("zio_control", "ext mask", None))
        self.grp_trg_stdattr.setTitle(_translate("zio_control", "Standard attributes", None))
        self.lbl_trg_nshot.setText(_translate("zio_control", "nshot", None))
        self.lbl_trg_pre.setText(_translate("zio_control", "pre-samples", None))
        self.lbl_trg_post.setText(_translate("zio_control", "post-samples", None))
        self.label_2.setText(_translate("zio_control", "version", None))
        self.grp_trg_extattr.setTitle(_translate("zio_control", "Extended attributes", None))
        self.tab_attributes.setTabText(self.tab_attributes.indexOf(self.tab_trg), _translate("zio_control", "Trigger", None))

